// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerPruneLibpodReader is a Reader for the ContainerPruneLibpod structure.
type ContainerPruneLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerPruneLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContainerPruneLibpodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewContainerPruneLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerPruneLibpodOK creates a ContainerPruneLibpodOK with default headers values
func NewContainerPruneLibpodOK() *ContainerPruneLibpodOK {
	return &ContainerPruneLibpodOK{}
}

/* ContainerPruneLibpodOK describes a response with status code 200, with default header values.

Prune containers
*/
type ContainerPruneLibpodOK struct {
	Payload []*models.LibpodContainersPruneReport
}

func (o *ContainerPruneLibpodOK) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/prune][%d] containerPruneLibpodOK  %+v", 200, o.Payload)
}
func (o *ContainerPruneLibpodOK) GetPayload() []*models.LibpodContainersPruneReport {
	return o.Payload
}

func (o *ContainerPruneLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerPruneLibpodInternalServerError creates a ContainerPruneLibpodInternalServerError with default headers values
func NewContainerPruneLibpodInternalServerError() *ContainerPruneLibpodInternalServerError {
	return &ContainerPruneLibpodInternalServerError{}
}

/* ContainerPruneLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerPruneLibpodInternalServerError struct {
	Payload *models.ContainerPruneLibpodInternalServerErrorBody
}

func (o *ContainerPruneLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/prune][%d] containerPruneLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerPruneLibpodInternalServerError) GetPayload() *models.ContainerPruneLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerPruneLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerPruneLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
