// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerArchiveLibpodReader is a Reader for the ContainerArchiveLibpod structure.
type ContainerArchiveLibpodReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *ContainerArchiveLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContainerArchiveLibpodOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewContainerArchiveLibpodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewContainerArchiveLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerArchiveLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerArchiveLibpodOK creates a ContainerArchiveLibpodOK with default headers values
func NewContainerArchiveLibpodOK(writer io.Writer) *ContainerArchiveLibpodOK {
	return &ContainerArchiveLibpodOK{

		Payload: writer,
	}
}

/* ContainerArchiveLibpodOK describes a response with status code 200, with default header values.

no error
*/
type ContainerArchiveLibpodOK struct {
	Payload io.Writer
}

func (o *ContainerArchiveLibpodOK) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/archive][%d] containerArchiveLibpodOK  %+v", 200, o.Payload)
}
func (o *ContainerArchiveLibpodOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *ContainerArchiveLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerArchiveLibpodBadRequest creates a ContainerArchiveLibpodBadRequest with default headers values
func NewContainerArchiveLibpodBadRequest() *ContainerArchiveLibpodBadRequest {
	return &ContainerArchiveLibpodBadRequest{}
}

/* ContainerArchiveLibpodBadRequest describes a response with status code 400, with default header values.

Bad parameter in request
*/
type ContainerArchiveLibpodBadRequest struct {
	Payload *models.ContainerArchiveLibpodBadRequestBody
}

func (o *ContainerArchiveLibpodBadRequest) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/archive][%d] containerArchiveLibpodBadRequest  %+v", 400, o.Payload)
}
func (o *ContainerArchiveLibpodBadRequest) GetPayload() *models.ContainerArchiveLibpodBadRequestBody {
	return o.Payload
}

func (o *ContainerArchiveLibpodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerArchiveLibpodBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerArchiveLibpodNotFound creates a ContainerArchiveLibpodNotFound with default headers values
func NewContainerArchiveLibpodNotFound() *ContainerArchiveLibpodNotFound {
	return &ContainerArchiveLibpodNotFound{}
}

/* ContainerArchiveLibpodNotFound describes a response with status code 404, with default header values.

No such container
*/
type ContainerArchiveLibpodNotFound struct {
	Payload *models.ContainerArchiveLibpodNotFoundBody
}

func (o *ContainerArchiveLibpodNotFound) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/archive][%d] containerArchiveLibpodNotFound  %+v", 404, o.Payload)
}
func (o *ContainerArchiveLibpodNotFound) GetPayload() *models.ContainerArchiveLibpodNotFoundBody {
	return o.Payload
}

func (o *ContainerArchiveLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerArchiveLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerArchiveLibpodInternalServerError creates a ContainerArchiveLibpodInternalServerError with default headers values
func NewContainerArchiveLibpodInternalServerError() *ContainerArchiveLibpodInternalServerError {
	return &ContainerArchiveLibpodInternalServerError{}
}

/* ContainerArchiveLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerArchiveLibpodInternalServerError struct {
	Payload *models.ContainerArchiveLibpodInternalServerErrorBody
}

func (o *ContainerArchiveLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/archive][%d] containerArchiveLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerArchiveLibpodInternalServerError) GetPayload() *models.ContainerArchiveLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerArchiveLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerArchiveLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
