// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerKillLibpodReader is a Reader for the ContainerKillLibpod structure.
type ContainerKillLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerKillLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewContainerKillLibpodNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewContainerKillLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewContainerKillLibpodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerKillLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerKillLibpodNoContent creates a ContainerKillLibpodNoContent with default headers values
func NewContainerKillLibpodNoContent() *ContainerKillLibpodNoContent {
	return &ContainerKillLibpodNoContent{}
}

/* ContainerKillLibpodNoContent describes a response with status code 204, with default header values.

no error
*/
type ContainerKillLibpodNoContent struct {
}

func (o *ContainerKillLibpodNoContent) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/kill][%d] containerKillLibpodNoContent ", 204)
}

func (o *ContainerKillLibpodNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerKillLibpodNotFound creates a ContainerKillLibpodNotFound with default headers values
func NewContainerKillLibpodNotFound() *ContainerKillLibpodNotFound {
	return &ContainerKillLibpodNotFound{}
}

/* ContainerKillLibpodNotFound describes a response with status code 404, with default header values.

No such container
*/
type ContainerKillLibpodNotFound struct {
	Payload *models.ContainerKillLibpodNotFoundBody
}

func (o *ContainerKillLibpodNotFound) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/kill][%d] containerKillLibpodNotFound  %+v", 404, o.Payload)
}
func (o *ContainerKillLibpodNotFound) GetPayload() *models.ContainerKillLibpodNotFoundBody {
	return o.Payload
}

func (o *ContainerKillLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerKillLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerKillLibpodConflict creates a ContainerKillLibpodConflict with default headers values
func NewContainerKillLibpodConflict() *ContainerKillLibpodConflict {
	return &ContainerKillLibpodConflict{}
}

/* ContainerKillLibpodConflict describes a response with status code 409, with default header values.

Conflict error in operation
*/
type ContainerKillLibpodConflict struct {
	Payload *models.ContainerKillLibpodConflictBody
}

func (o *ContainerKillLibpodConflict) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/kill][%d] containerKillLibpodConflict  %+v", 409, o.Payload)
}
func (o *ContainerKillLibpodConflict) GetPayload() *models.ContainerKillLibpodConflictBody {
	return o.Payload
}

func (o *ContainerKillLibpodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerKillLibpodConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerKillLibpodInternalServerError creates a ContainerKillLibpodInternalServerError with default headers values
func NewContainerKillLibpodInternalServerError() *ContainerKillLibpodInternalServerError {
	return &ContainerKillLibpodInternalServerError{}
}

/* ContainerKillLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerKillLibpodInternalServerError struct {
	Payload *models.ContainerKillLibpodInternalServerErrorBody
}

func (o *ContainerKillLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/kill][%d] containerKillLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerKillLibpodInternalServerError) GetPayload() *models.ContainerKillLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerKillLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerKillLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
