// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerDeleteReader is a Reader for the ContainerDelete structure.
type ContainerDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewContainerDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewContainerDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewContainerDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewContainerDeleteConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerDeleteNoContent creates a ContainerDeleteNoContent with default headers values
func NewContainerDeleteNoContent() *ContainerDeleteNoContent {
	return &ContainerDeleteNoContent{}
}

/* ContainerDeleteNoContent describes a response with status code 204, with default header values.

no error
*/
type ContainerDeleteNoContent struct {
}

func (o *ContainerDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /containers/{name}][%d] containerDeleteNoContent ", 204)
}

func (o *ContainerDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerDeleteBadRequest creates a ContainerDeleteBadRequest with default headers values
func NewContainerDeleteBadRequest() *ContainerDeleteBadRequest {
	return &ContainerDeleteBadRequest{}
}

/* ContainerDeleteBadRequest describes a response with status code 400, with default header values.

Bad parameter in request
*/
type ContainerDeleteBadRequest struct {
	Payload *models.ContainerDeleteBadRequestBody
}

func (o *ContainerDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /containers/{name}][%d] containerDeleteBadRequest  %+v", 400, o.Payload)
}
func (o *ContainerDeleteBadRequest) GetPayload() *models.ContainerDeleteBadRequestBody {
	return o.Payload
}

func (o *ContainerDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerDeleteBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerDeleteNotFound creates a ContainerDeleteNotFound with default headers values
func NewContainerDeleteNotFound() *ContainerDeleteNotFound {
	return &ContainerDeleteNotFound{}
}

/* ContainerDeleteNotFound describes a response with status code 404, with default header values.

No such container
*/
type ContainerDeleteNotFound struct {
	Payload *models.ContainerDeleteNotFoundBody
}

func (o *ContainerDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /containers/{name}][%d] containerDeleteNotFound  %+v", 404, o.Payload)
}
func (o *ContainerDeleteNotFound) GetPayload() *models.ContainerDeleteNotFoundBody {
	return o.Payload
}

func (o *ContainerDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerDeleteNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerDeleteConflict creates a ContainerDeleteConflict with default headers values
func NewContainerDeleteConflict() *ContainerDeleteConflict {
	return &ContainerDeleteConflict{}
}

/* ContainerDeleteConflict describes a response with status code 409, with default header values.

Conflict error in operation
*/
type ContainerDeleteConflict struct {
	Payload *models.ContainerDeleteConflictBody
}

func (o *ContainerDeleteConflict) Error() string {
	return fmt.Sprintf("[DELETE /containers/{name}][%d] containerDeleteConflict  %+v", 409, o.Payload)
}
func (o *ContainerDeleteConflict) GetPayload() *models.ContainerDeleteConflictBody {
	return o.Payload
}

func (o *ContainerDeleteConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerDeleteConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerDeleteInternalServerError creates a ContainerDeleteInternalServerError with default headers values
func NewContainerDeleteInternalServerError() *ContainerDeleteInternalServerError {
	return &ContainerDeleteInternalServerError{}
}

/* ContainerDeleteInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerDeleteInternalServerError struct {
	Payload *models.ContainerDeleteInternalServerErrorBody
}

func (o *ContainerDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /containers/{name}][%d] containerDeleteInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerDeleteInternalServerError) GetPayload() *models.ContainerDeleteInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerDeleteInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
