// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerKillReader is a Reader for the ContainerKill structure.
type ContainerKillReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerKillReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewContainerKillNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewContainerKillNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewContainerKillConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerKillInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerKillNoContent creates a ContainerKillNoContent with default headers values
func NewContainerKillNoContent() *ContainerKillNoContent {
	return &ContainerKillNoContent{}
}

/* ContainerKillNoContent describes a response with status code 204, with default header values.

no error
*/
type ContainerKillNoContent struct {
}

func (o *ContainerKillNoContent) Error() string {
	return fmt.Sprintf("[POST /containers/{name}/kill][%d] containerKillNoContent ", 204)
}

func (o *ContainerKillNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerKillNotFound creates a ContainerKillNotFound with default headers values
func NewContainerKillNotFound() *ContainerKillNotFound {
	return &ContainerKillNotFound{}
}

/* ContainerKillNotFound describes a response with status code 404, with default header values.

No such container
*/
type ContainerKillNotFound struct {
	Payload *models.ContainerKillNotFoundBody
}

func (o *ContainerKillNotFound) Error() string {
	return fmt.Sprintf("[POST /containers/{name}/kill][%d] containerKillNotFound  %+v", 404, o.Payload)
}
func (o *ContainerKillNotFound) GetPayload() *models.ContainerKillNotFoundBody {
	return o.Payload
}

func (o *ContainerKillNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerKillNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerKillConflict creates a ContainerKillConflict with default headers values
func NewContainerKillConflict() *ContainerKillConflict {
	return &ContainerKillConflict{}
}

/* ContainerKillConflict describes a response with status code 409, with default header values.

Conflict error in operation
*/
type ContainerKillConflict struct {
	Payload *models.ContainerKillConflictBody
}

func (o *ContainerKillConflict) Error() string {
	return fmt.Sprintf("[POST /containers/{name}/kill][%d] containerKillConflict  %+v", 409, o.Payload)
}
func (o *ContainerKillConflict) GetPayload() *models.ContainerKillConflictBody {
	return o.Payload
}

func (o *ContainerKillConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerKillConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerKillInternalServerError creates a ContainerKillInternalServerError with default headers values
func NewContainerKillInternalServerError() *ContainerKillInternalServerError {
	return &ContainerKillInternalServerError{}
}

/* ContainerKillInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerKillInternalServerError struct {
	Payload *models.ContainerKillInternalServerErrorBody
}

func (o *ContainerKillInternalServerError) Error() string {
	return fmt.Sprintf("[POST /containers/{name}/kill][%d] containerKillInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerKillInternalServerError) GetPayload() *models.ContainerKillInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerKillInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerKillInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
