// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerHealthcheckLibpodReader is a Reader for the ContainerHealthcheckLibpod structure.
type ContainerHealthcheckLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerHealthcheckLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContainerHealthcheckLibpodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewContainerHealthcheckLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewContainerHealthcheckLibpodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerHealthcheckLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerHealthcheckLibpodOK creates a ContainerHealthcheckLibpodOK with default headers values
func NewContainerHealthcheckLibpodOK() *ContainerHealthcheckLibpodOK {
	return &ContainerHealthcheckLibpodOK{}
}

/* ContainerHealthcheckLibpodOK describes a response with status code 200, with default header values.

Healthcheck
*/
type ContainerHealthcheckLibpodOK struct {
	Payload *models.ContainerHealthcheckLibpodOKBody
}

func (o *ContainerHealthcheckLibpodOK) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/healthcheck][%d] containerHealthcheckLibpodOK  %+v", 200, o.Payload)
}
func (o *ContainerHealthcheckLibpodOK) GetPayload() *models.ContainerHealthcheckLibpodOKBody {
	return o.Payload
}

func (o *ContainerHealthcheckLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerHealthcheckLibpodOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerHealthcheckLibpodNotFound creates a ContainerHealthcheckLibpodNotFound with default headers values
func NewContainerHealthcheckLibpodNotFound() *ContainerHealthcheckLibpodNotFound {
	return &ContainerHealthcheckLibpodNotFound{}
}

/* ContainerHealthcheckLibpodNotFound describes a response with status code 404, with default header values.

No such container
*/
type ContainerHealthcheckLibpodNotFound struct {
	Payload *models.ContainerHealthcheckLibpodNotFoundBody
}

func (o *ContainerHealthcheckLibpodNotFound) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/healthcheck][%d] containerHealthcheckLibpodNotFound  %+v", 404, o.Payload)
}
func (o *ContainerHealthcheckLibpodNotFound) GetPayload() *models.ContainerHealthcheckLibpodNotFoundBody {
	return o.Payload
}

func (o *ContainerHealthcheckLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerHealthcheckLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerHealthcheckLibpodConflict creates a ContainerHealthcheckLibpodConflict with default headers values
func NewContainerHealthcheckLibpodConflict() *ContainerHealthcheckLibpodConflict {
	return &ContainerHealthcheckLibpodConflict{}
}

/* ContainerHealthcheckLibpodConflict describes a response with status code 409, with default header values.

container has no healthcheck or is not running
*/
type ContainerHealthcheckLibpodConflict struct {
}

func (o *ContainerHealthcheckLibpodConflict) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/healthcheck][%d] containerHealthcheckLibpodConflict ", 409)
}

func (o *ContainerHealthcheckLibpodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerHealthcheckLibpodInternalServerError creates a ContainerHealthcheckLibpodInternalServerError with default headers values
func NewContainerHealthcheckLibpodInternalServerError() *ContainerHealthcheckLibpodInternalServerError {
	return &ContainerHealthcheckLibpodInternalServerError{}
}

/* ContainerHealthcheckLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerHealthcheckLibpodInternalServerError struct {
	Payload *models.ContainerHealthcheckLibpodInternalServerErrorBody
}

func (o *ContainerHealthcheckLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/containers/{name}/healthcheck][%d] containerHealthcheckLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerHealthcheckLibpodInternalServerError) GetPayload() *models.ContainerHealthcheckLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerHealthcheckLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerHealthcheckLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
