// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ContainerPauseLibpodReader is a Reader for the ContainerPauseLibpod structure.
type ContainerPauseLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContainerPauseLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewContainerPauseLibpodNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewContainerPauseLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewContainerPauseLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContainerPauseLibpodNoContent creates a ContainerPauseLibpodNoContent with default headers values
func NewContainerPauseLibpodNoContent() *ContainerPauseLibpodNoContent {
	return &ContainerPauseLibpodNoContent{}
}

/* ContainerPauseLibpodNoContent describes a response with status code 204, with default header values.

no error
*/
type ContainerPauseLibpodNoContent struct {
}

func (o *ContainerPauseLibpodNoContent) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/pause][%d] containerPauseLibpodNoContent ", 204)
}

func (o *ContainerPauseLibpodNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewContainerPauseLibpodNotFound creates a ContainerPauseLibpodNotFound with default headers values
func NewContainerPauseLibpodNotFound() *ContainerPauseLibpodNotFound {
	return &ContainerPauseLibpodNotFound{}
}

/* ContainerPauseLibpodNotFound describes a response with status code 404, with default header values.

No such container
*/
type ContainerPauseLibpodNotFound struct {
	Payload *models.ContainerPauseLibpodNotFoundBody
}

func (o *ContainerPauseLibpodNotFound) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/pause][%d] containerPauseLibpodNotFound  %+v", 404, o.Payload)
}
func (o *ContainerPauseLibpodNotFound) GetPayload() *models.ContainerPauseLibpodNotFoundBody {
	return o.Payload
}

func (o *ContainerPauseLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerPauseLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContainerPauseLibpodInternalServerError creates a ContainerPauseLibpodInternalServerError with default headers values
func NewContainerPauseLibpodInternalServerError() *ContainerPauseLibpodInternalServerError {
	return &ContainerPauseLibpodInternalServerError{}
}

/* ContainerPauseLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ContainerPauseLibpodInternalServerError struct {
	Payload *models.ContainerPauseLibpodInternalServerErrorBody
}

func (o *ContainerPauseLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/containers/{name}/pause][%d] containerPauseLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ContainerPauseLibpodInternalServerError) GetPayload() *models.ContainerPauseLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ContainerPauseLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContainerPauseLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
