// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ExecInspectReader is a Reader for the ExecInspect structure.
type ExecInspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExecInspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExecInspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewExecInspectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExecInspectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExecInspectOK creates a ExecInspectOK with default headers values
func NewExecInspectOK() *ExecInspectOK {
	return &ExecInspectOK{}
}

/* ExecInspectOK describes a response with status code 200, with default header values.

Inspect response
*/
type ExecInspectOK struct {
	Payload *models.ExecInspectOKBody
}

func (o *ExecInspectOK) Error() string {
	return fmt.Sprintf("[GET /exec/{id}/json][%d] execInspectOK  %+v", 200, o.Payload)
}
func (o *ExecInspectOK) GetPayload() *models.ExecInspectOKBody {
	return o.Payload
}

func (o *ExecInspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExecInspectOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecInspectNotFound creates a ExecInspectNotFound with default headers values
func NewExecInspectNotFound() *ExecInspectNotFound {
	return &ExecInspectNotFound{}
}

/* ExecInspectNotFound describes a response with status code 404, with default header values.

No such exec instance
*/
type ExecInspectNotFound struct {
	Payload *models.ExecInspectNotFoundBody
}

func (o *ExecInspectNotFound) Error() string {
	return fmt.Sprintf("[GET /exec/{id}/json][%d] execInspectNotFound  %+v", 404, o.Payload)
}
func (o *ExecInspectNotFound) GetPayload() *models.ExecInspectNotFoundBody {
	return o.Payload
}

func (o *ExecInspectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExecInspectNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExecInspectInternalServerError creates a ExecInspectInternalServerError with default headers values
func NewExecInspectInternalServerError() *ExecInspectInternalServerError {
	return &ExecInspectInternalServerError{}
}

/* ExecInspectInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ExecInspectInternalServerError struct {
	Payload *models.ExecInspectInternalServerErrorBody
}

func (o *ExecInspectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /exec/{id}/json][%d] execInspectInternalServerError  %+v", 500, o.Payload)
}
func (o *ExecInspectInternalServerError) GetPayload() *models.ExecInspectInternalServerErrorBody {
	return o.Payload
}

func (o *ExecInspectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExecInspectInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
