// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// NewExecStartLibpodParams creates a new ExecStartLibpodParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExecStartLibpodParams() *ExecStartLibpodParams {
	return &ExecStartLibpodParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExecStartLibpodParamsWithTimeout creates a new ExecStartLibpodParams object
// with the ability to set a timeout on a request.
func NewExecStartLibpodParamsWithTimeout(timeout time.Duration) *ExecStartLibpodParams {
	return &ExecStartLibpodParams{
		timeout: timeout,
	}
}

// NewExecStartLibpodParamsWithContext creates a new ExecStartLibpodParams object
// with the ability to set a context for a request.
func NewExecStartLibpodParamsWithContext(ctx context.Context) *ExecStartLibpodParams {
	return &ExecStartLibpodParams{
		Context: ctx,
	}
}

// NewExecStartLibpodParamsWithHTTPClient creates a new ExecStartLibpodParams object
// with the ability to set a custom HTTPClient for a request.
func NewExecStartLibpodParamsWithHTTPClient(client *http.Client) *ExecStartLibpodParams {
	return &ExecStartLibpodParams{
		HTTPClient: client,
	}
}

/* ExecStartLibpodParams contains all the parameters to send to the API endpoint
   for the exec start libpod operation.

   Typically these are written to a http.Request.
*/
type ExecStartLibpodParams struct {

	/* Control.

	   Attributes for start
	*/
	Control *models.ExecStartLibpodParamsBody

	/* ID.

	   Exec instance ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the exec start libpod params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExecStartLibpodParams) WithDefaults() *ExecStartLibpodParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the exec start libpod params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExecStartLibpodParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the exec start libpod params
func (o *ExecStartLibpodParams) WithTimeout(timeout time.Duration) *ExecStartLibpodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the exec start libpod params
func (o *ExecStartLibpodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the exec start libpod params
func (o *ExecStartLibpodParams) WithContext(ctx context.Context) *ExecStartLibpodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the exec start libpod params
func (o *ExecStartLibpodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the exec start libpod params
func (o *ExecStartLibpodParams) WithHTTPClient(client *http.Client) *ExecStartLibpodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the exec start libpod params
func (o *ExecStartLibpodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithControl adds the control to the exec start libpod params
func (o *ExecStartLibpodParams) WithControl(control *models.ExecStartLibpodParamsBody) *ExecStartLibpodParams {
	o.SetControl(control)
	return o
}

// SetControl adds the control to the exec start libpod params
func (o *ExecStartLibpodParams) SetControl(control *models.ExecStartLibpodParamsBody) {
	o.Control = control
}

// WithID adds the id to the exec start libpod params
func (o *ExecStartLibpodParams) WithID(id string) *ExecStartLibpodParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the exec start libpod params
func (o *ExecStartLibpodParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ExecStartLibpodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Control != nil {
		if err := r.SetBodyParam(o.Control); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
