// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ImageHistoryLibpodReader is a Reader for the ImageHistoryLibpod structure.
type ImageHistoryLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImageHistoryLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewImageHistoryLibpodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewImageHistoryLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewImageHistoryLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImageHistoryLibpodOK creates a ImageHistoryLibpodOK with default headers values
func NewImageHistoryLibpodOK() *ImageHistoryLibpodOK {
	return &ImageHistoryLibpodOK{}
}

/* ImageHistoryLibpodOK describes a response with status code 200, with default header values.

History response
*/
type ImageHistoryLibpodOK struct {
	Payload *models.ImageHistoryLibpodOKBody
}

func (o *ImageHistoryLibpodOK) Error() string {
	return fmt.Sprintf("[GET /libpod/images/{name}/history][%d] imageHistoryLibpodOK  %+v", 200, o.Payload)
}
func (o *ImageHistoryLibpodOK) GetPayload() *models.ImageHistoryLibpodOKBody {
	return o.Payload
}

func (o *ImageHistoryLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageHistoryLibpodOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageHistoryLibpodNotFound creates a ImageHistoryLibpodNotFound with default headers values
func NewImageHistoryLibpodNotFound() *ImageHistoryLibpodNotFound {
	return &ImageHistoryLibpodNotFound{}
}

/* ImageHistoryLibpodNotFound describes a response with status code 404, with default header values.

No such image
*/
type ImageHistoryLibpodNotFound struct {
	Payload *models.ImageHistoryLibpodNotFoundBody
}

func (o *ImageHistoryLibpodNotFound) Error() string {
	return fmt.Sprintf("[GET /libpod/images/{name}/history][%d] imageHistoryLibpodNotFound  %+v", 404, o.Payload)
}
func (o *ImageHistoryLibpodNotFound) GetPayload() *models.ImageHistoryLibpodNotFoundBody {
	return o.Payload
}

func (o *ImageHistoryLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageHistoryLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageHistoryLibpodInternalServerError creates a ImageHistoryLibpodInternalServerError with default headers values
func NewImageHistoryLibpodInternalServerError() *ImageHistoryLibpodInternalServerError {
	return &ImageHistoryLibpodInternalServerError{}
}

/* ImageHistoryLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ImageHistoryLibpodInternalServerError struct {
	Payload *models.ImageHistoryLibpodInternalServerErrorBody
}

func (o *ImageHistoryLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/images/{name}/history][%d] imageHistoryLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ImageHistoryLibpodInternalServerError) GetPayload() *models.ImageHistoryLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ImageHistoryLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageHistoryLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
