// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ImageUntagLibpodReader is a Reader for the ImageUntagLibpod structure.
type ImageUntagLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImageUntagLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewImageUntagLibpodCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewImageUntagLibpodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewImageUntagLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewImageUntagLibpodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewImageUntagLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImageUntagLibpodCreated creates a ImageUntagLibpodCreated with default headers values
func NewImageUntagLibpodCreated() *ImageUntagLibpodCreated {
	return &ImageUntagLibpodCreated{}
}

/* ImageUntagLibpodCreated describes a response with status code 201, with default header values.

no error
*/
type ImageUntagLibpodCreated struct {
}

func (o *ImageUntagLibpodCreated) Error() string {
	return fmt.Sprintf("[POST /libpod/images/{name}/untag][%d] imageUntagLibpodCreated ", 201)
}

func (o *ImageUntagLibpodCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewImageUntagLibpodBadRequest creates a ImageUntagLibpodBadRequest with default headers values
func NewImageUntagLibpodBadRequest() *ImageUntagLibpodBadRequest {
	return &ImageUntagLibpodBadRequest{}
}

/* ImageUntagLibpodBadRequest describes a response with status code 400, with default header values.

Bad parameter in request
*/
type ImageUntagLibpodBadRequest struct {
	Payload *models.ImageUntagLibpodBadRequestBody
}

func (o *ImageUntagLibpodBadRequest) Error() string {
	return fmt.Sprintf("[POST /libpod/images/{name}/untag][%d] imageUntagLibpodBadRequest  %+v", 400, o.Payload)
}
func (o *ImageUntagLibpodBadRequest) GetPayload() *models.ImageUntagLibpodBadRequestBody {
	return o.Payload
}

func (o *ImageUntagLibpodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageUntagLibpodBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageUntagLibpodNotFound creates a ImageUntagLibpodNotFound with default headers values
func NewImageUntagLibpodNotFound() *ImageUntagLibpodNotFound {
	return &ImageUntagLibpodNotFound{}
}

/* ImageUntagLibpodNotFound describes a response with status code 404, with default header values.

No such image
*/
type ImageUntagLibpodNotFound struct {
	Payload *models.ImageUntagLibpodNotFoundBody
}

func (o *ImageUntagLibpodNotFound) Error() string {
	return fmt.Sprintf("[POST /libpod/images/{name}/untag][%d] imageUntagLibpodNotFound  %+v", 404, o.Payload)
}
func (o *ImageUntagLibpodNotFound) GetPayload() *models.ImageUntagLibpodNotFoundBody {
	return o.Payload
}

func (o *ImageUntagLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageUntagLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageUntagLibpodConflict creates a ImageUntagLibpodConflict with default headers values
func NewImageUntagLibpodConflict() *ImageUntagLibpodConflict {
	return &ImageUntagLibpodConflict{}
}

/* ImageUntagLibpodConflict describes a response with status code 409, with default header values.

Conflict error in operation
*/
type ImageUntagLibpodConflict struct {
	Payload *models.ImageUntagLibpodConflictBody
}

func (o *ImageUntagLibpodConflict) Error() string {
	return fmt.Sprintf("[POST /libpod/images/{name}/untag][%d] imageUntagLibpodConflict  %+v", 409, o.Payload)
}
func (o *ImageUntagLibpodConflict) GetPayload() *models.ImageUntagLibpodConflictBody {
	return o.Payload
}

func (o *ImageUntagLibpodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageUntagLibpodConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageUntagLibpodInternalServerError creates a ImageUntagLibpodInternalServerError with default headers values
func NewImageUntagLibpodInternalServerError() *ImageUntagLibpodInternalServerError {
	return &ImageUntagLibpodInternalServerError{}
}

/* ImageUntagLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ImageUntagLibpodInternalServerError struct {
	Payload *models.ImageUntagLibpodInternalServerErrorBody
}

func (o *ImageUntagLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/images/{name}/untag][%d] imageUntagLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *ImageUntagLibpodInternalServerError) GetPayload() *models.ImageUntagLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *ImageUntagLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageUntagLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
