// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// ImageDeleteReader is a Reader for the ImageDelete structure.
type ImageDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ImageDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewImageDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewImageDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewImageDeleteConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewImageDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewImageDeleteOK creates a ImageDeleteOK with default headers values
func NewImageDeleteOK() *ImageDeleteOK {
	return &ImageDeleteOK{}
}

/* ImageDeleteOK describes a response with status code 200, with default header values.

Delete response
*/
type ImageDeleteOK struct {
	Payload []*models.ImageDeleteOKBodyItems
}

func (o *ImageDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /images/{name}][%d] imageDeleteOK  %+v", 200, o.Payload)
}
func (o *ImageDeleteOK) GetPayload() []*models.ImageDeleteOKBodyItems {
	return o.Payload
}

func (o *ImageDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageDeleteNotFound creates a ImageDeleteNotFound with default headers values
func NewImageDeleteNotFound() *ImageDeleteNotFound {
	return &ImageDeleteNotFound{}
}

/* ImageDeleteNotFound describes a response with status code 404, with default header values.

No such image
*/
type ImageDeleteNotFound struct {
	Payload *models.ImageDeleteNotFoundBody
}

func (o *ImageDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /images/{name}][%d] imageDeleteNotFound  %+v", 404, o.Payload)
}
func (o *ImageDeleteNotFound) GetPayload() *models.ImageDeleteNotFoundBody {
	return o.Payload
}

func (o *ImageDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageDeleteNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageDeleteConflict creates a ImageDeleteConflict with default headers values
func NewImageDeleteConflict() *ImageDeleteConflict {
	return &ImageDeleteConflict{}
}

/* ImageDeleteConflict describes a response with status code 409, with default header values.

Conflict error in operation
*/
type ImageDeleteConflict struct {
	Payload *models.ImageDeleteConflictBody
}

func (o *ImageDeleteConflict) Error() string {
	return fmt.Sprintf("[DELETE /images/{name}][%d] imageDeleteConflict  %+v", 409, o.Payload)
}
func (o *ImageDeleteConflict) GetPayload() *models.ImageDeleteConflictBody {
	return o.Payload
}

func (o *ImageDeleteConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageDeleteConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewImageDeleteInternalServerError creates a ImageDeleteInternalServerError with default headers values
func NewImageDeleteInternalServerError() *ImageDeleteInternalServerError {
	return &ImageDeleteInternalServerError{}
}

/* ImageDeleteInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ImageDeleteInternalServerError struct {
	Payload *models.ImageDeleteInternalServerErrorBody
}

func (o *ImageDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /images/{name}][%d] imageDeleteInternalServerError  %+v", 500, o.Payload)
}
func (o *ImageDeleteInternalServerError) GetPayload() *models.ImageDeleteInternalServerErrorBody {
	return o.Payload
}

func (o *ImageDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageDeleteInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
