// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// NetworkCreateLibpodReader is a Reader for the NetworkCreateLibpod structure.
type NetworkCreateLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetworkCreateLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNetworkCreateLibpodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNetworkCreateLibpodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewNetworkCreateLibpodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNetworkCreateLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNetworkCreateLibpodOK creates a NetworkCreateLibpodOK with default headers values
func NewNetworkCreateLibpodOK() *NetworkCreateLibpodOK {
	return &NetworkCreateLibpodOK{}
}

/* NetworkCreateLibpodOK describes a response with status code 200, with default header values.

Network create
*/
type NetworkCreateLibpodOK struct {
	Payload *models.Network
}

func (o *NetworkCreateLibpodOK) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] networkCreateLibpodOK  %+v", 200, o.Payload)
}
func (o *NetworkCreateLibpodOK) GetPayload() *models.Network {
	return o.Payload
}

func (o *NetworkCreateLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Network)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkCreateLibpodBadRequest creates a NetworkCreateLibpodBadRequest with default headers values
func NewNetworkCreateLibpodBadRequest() *NetworkCreateLibpodBadRequest {
	return &NetworkCreateLibpodBadRequest{}
}

/* NetworkCreateLibpodBadRequest describes a response with status code 400, with default header values.

Bad parameter in request
*/
type NetworkCreateLibpodBadRequest struct {
	Payload *models.NetworkCreateLibpodBadRequestBody
}

func (o *NetworkCreateLibpodBadRequest) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] networkCreateLibpodBadRequest  %+v", 400, o.Payload)
}
func (o *NetworkCreateLibpodBadRequest) GetPayload() *models.NetworkCreateLibpodBadRequestBody {
	return o.Payload
}

func (o *NetworkCreateLibpodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkCreateLibpodBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkCreateLibpodConflict creates a NetworkCreateLibpodConflict with default headers values
func NewNetworkCreateLibpodConflict() *NetworkCreateLibpodConflict {
	return &NetworkCreateLibpodConflict{}
}

/* NetworkCreateLibpodConflict describes a response with status code 409, with default header values.

Conflict error in operation
*/
type NetworkCreateLibpodConflict struct {
	Payload *models.NetworkCreateLibpodConflictBody
}

func (o *NetworkCreateLibpodConflict) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] networkCreateLibpodConflict  %+v", 409, o.Payload)
}
func (o *NetworkCreateLibpodConflict) GetPayload() *models.NetworkCreateLibpodConflictBody {
	return o.Payload
}

func (o *NetworkCreateLibpodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkCreateLibpodConflictBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNetworkCreateLibpodInternalServerError creates a NetworkCreateLibpodInternalServerError with default headers values
func NewNetworkCreateLibpodInternalServerError() *NetworkCreateLibpodInternalServerError {
	return &NetworkCreateLibpodInternalServerError{}
}

/* NetworkCreateLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type NetworkCreateLibpodInternalServerError struct {
	Payload *models.NetworkCreateLibpodInternalServerErrorBody
}

func (o *NetworkCreateLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/networks/create][%d] networkCreateLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *NetworkCreateLibpodInternalServerError) GetPayload() *models.NetworkCreateLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *NetworkCreateLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkCreateLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
