// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// PodUnpauseLibpodReader is a Reader for the PodUnpauseLibpod structure.
type PodUnpauseLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PodUnpauseLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPodUnpauseLibpodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewPodUnpauseLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPodUnpauseLibpodConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPodUnpauseLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPodUnpauseLibpodOK creates a PodUnpauseLibpodOK with default headers values
func NewPodUnpauseLibpodOK() *PodUnpauseLibpodOK {
	return &PodUnpauseLibpodOK{}
}

/* PodUnpauseLibpodOK describes a response with status code 200, with default header values.

Unpause pod
*/
type PodUnpauseLibpodOK struct {
	Payload *models.PodUnpauseReport
}

func (o *PodUnpauseLibpodOK) Error() string {
	return fmt.Sprintf("[POST /libpod/pods/{name}/unpause][%d] podUnpauseLibpodOK  %+v", 200, o.Payload)
}
func (o *PodUnpauseLibpodOK) GetPayload() *models.PodUnpauseReport {
	return o.Payload
}

func (o *PodUnpauseLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PodUnpauseReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPodUnpauseLibpodNotFound creates a PodUnpauseLibpodNotFound with default headers values
func NewPodUnpauseLibpodNotFound() *PodUnpauseLibpodNotFound {
	return &PodUnpauseLibpodNotFound{}
}

/* PodUnpauseLibpodNotFound describes a response with status code 404, with default header values.

No such pod
*/
type PodUnpauseLibpodNotFound struct {
	Payload *models.PodUnpauseLibpodNotFoundBody
}

func (o *PodUnpauseLibpodNotFound) Error() string {
	return fmt.Sprintf("[POST /libpod/pods/{name}/unpause][%d] podUnpauseLibpodNotFound  %+v", 404, o.Payload)
}
func (o *PodUnpauseLibpodNotFound) GetPayload() *models.PodUnpauseLibpodNotFoundBody {
	return o.Payload
}

func (o *PodUnpauseLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PodUnpauseLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPodUnpauseLibpodConflict creates a PodUnpauseLibpodConflict with default headers values
func NewPodUnpauseLibpodConflict() *PodUnpauseLibpodConflict {
	return &PodUnpauseLibpodConflict{}
}

/* PodUnpauseLibpodConflict describes a response with status code 409, with default header values.

Unpause pod
*/
type PodUnpauseLibpodConflict struct {
	Payload *models.PodUnpauseReport
}

func (o *PodUnpauseLibpodConflict) Error() string {
	return fmt.Sprintf("[POST /libpod/pods/{name}/unpause][%d] podUnpauseLibpodConflict  %+v", 409, o.Payload)
}
func (o *PodUnpauseLibpodConflict) GetPayload() *models.PodUnpauseReport {
	return o.Payload
}

func (o *PodUnpauseLibpodConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PodUnpauseReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPodUnpauseLibpodInternalServerError creates a PodUnpauseLibpodInternalServerError with default headers values
func NewPodUnpauseLibpodInternalServerError() *PodUnpauseLibpodInternalServerError {
	return &PodUnpauseLibpodInternalServerError{}
}

/* PodUnpauseLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PodUnpauseLibpodInternalServerError struct {
	Payload *models.PodUnpauseLibpodInternalServerErrorBody
}

func (o *PodUnpauseLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /libpod/pods/{name}/unpause][%d] podUnpauseLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *PodUnpauseLibpodInternalServerError) GetPayload() *models.PodUnpauseLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *PodUnpauseLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PodUnpauseLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
