// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/project0/terraform-provider-podman/api/models"
)

// VolumeInspectLibpodReader is a Reader for the VolumeInspectLibpod structure.
type VolumeInspectLibpodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VolumeInspectLibpodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVolumeInspectLibpodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewVolumeInspectLibpodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewVolumeInspectLibpodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewVolumeInspectLibpodOK creates a VolumeInspectLibpodOK with default headers values
func NewVolumeInspectLibpodOK() *VolumeInspectLibpodOK {
	return &VolumeInspectLibpodOK{}
}

/* VolumeInspectLibpodOK describes a response with status code 200, with default header values.

Volume create response
*/
type VolumeInspectLibpodOK struct {
	Payload *models.VolumeInspectLibpodOKBody
}

func (o *VolumeInspectLibpodOK) Error() string {
	return fmt.Sprintf("[GET /libpod/volumes/{name}/json][%d] volumeInspectLibpodOK  %+v", 200, o.Payload)
}
func (o *VolumeInspectLibpodOK) GetPayload() *models.VolumeInspectLibpodOKBody {
	return o.Payload
}

func (o *VolumeInspectLibpodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeInspectLibpodOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVolumeInspectLibpodNotFound creates a VolumeInspectLibpodNotFound with default headers values
func NewVolumeInspectLibpodNotFound() *VolumeInspectLibpodNotFound {
	return &VolumeInspectLibpodNotFound{}
}

/* VolumeInspectLibpodNotFound describes a response with status code 404, with default header values.

No such volume
*/
type VolumeInspectLibpodNotFound struct {
	Payload *models.VolumeInspectLibpodNotFoundBody
}

func (o *VolumeInspectLibpodNotFound) Error() string {
	return fmt.Sprintf("[GET /libpod/volumes/{name}/json][%d] volumeInspectLibpodNotFound  %+v", 404, o.Payload)
}
func (o *VolumeInspectLibpodNotFound) GetPayload() *models.VolumeInspectLibpodNotFoundBody {
	return o.Payload
}

func (o *VolumeInspectLibpodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeInspectLibpodNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVolumeInspectLibpodInternalServerError creates a VolumeInspectLibpodInternalServerError with default headers values
func NewVolumeInspectLibpodInternalServerError() *VolumeInspectLibpodInternalServerError {
	return &VolumeInspectLibpodInternalServerError{}
}

/* VolumeInspectLibpodInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type VolumeInspectLibpodInternalServerError struct {
	Payload *models.VolumeInspectLibpodInternalServerErrorBody
}

func (o *VolumeInspectLibpodInternalServerError) Error() string {
	return fmt.Sprintf("[GET /libpod/volumes/{name}/json][%d] volumeInspectLibpodInternalServerError  %+v", 500, o.Payload)
}
func (o *VolumeInspectLibpodInternalServerError) GetPayload() *models.VolumeInspectLibpodInternalServerErrorBody {
	return o.Payload
}

func (o *VolumeInspectLibpodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeInspectLibpodInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
