// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ComponentVersion ComponentVersion describes the version information for a specific component.
//
// swagger:model ComponentVersion
type ComponentVersion struct {

	// details
	Details map[string]string `json:"Details,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// version
	Version string `json:"Version,omitempty"`
}

// Validate validates this component version
func (m *ComponentVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this component version based on context it is used
func (m *ComponentVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ComponentVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ComponentVersion) UnmarshalBinary(b []byte) error {
	var res ComponentVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
