// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContainerCreateLibpodCreatedBody container create libpod created body
//
// swagger:model containerCreateLibpodCreatedBody
type ContainerCreateLibpodCreatedBody struct {

	// ID of the container created
	// Required: true
	ID *string `json:"Id"`

	// Warnings during container creation
	// Required: true
	Warnings []string `json:"Warnings"`
}

// Validate validates this container create libpod created body
func (m *ContainerCreateLibpodCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWarnings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerCreateLibpodCreatedBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("Id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ContainerCreateLibpodCreatedBody) validateWarnings(formats strfmt.Registry) error {

	if err := validate.Required("Warnings", "body", m.Warnings); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this container create libpod created body based on context it is used
func (m *ContainerCreateLibpodCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ContainerCreateLibpodCreatedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerCreateLibpodCreatedBody) UnmarshalBinary(b []byte) error {
	var res ContainerCreateLibpodCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
