// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContainerWaitOKBodyOAIGen container wait o k body OAI gen
//
// swagger:model containerWaitOKBodyOAIGen
type ContainerWaitOKBodyOAIGen struct {

	// error
	Error *ContainerWaitOKBodyErrorOAIGen `json:"Error,omitempty"`

	// container exit code
	StatusCode int64 `json:"StatusCode,omitempty"`
}

// Validate validates this container wait o k body OAI gen
func (m *ContainerWaitOKBodyOAIGen) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerWaitOKBodyOAIGen) validateError(formats strfmt.Registry) error {
	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Error")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this container wait o k body OAI gen based on the context it is used
func (m *ContainerWaitOKBodyOAIGen) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerWaitOKBodyOAIGen) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if m.Error != nil {
		if err := m.Error.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Error")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Error")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContainerWaitOKBodyOAIGen) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerWaitOKBodyOAIGen) UnmarshalBinary(b []byte) error {
	var res ContainerWaitOKBodyOAIGen
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
