// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InspectLogConfig InspectLogConfig holds information about a container's configured log driver
//
// swagger:model InspectLogConfig
type InspectLogConfig struct {

	// config
	Config map[string]string `json:"Config,omitempty"`

	// Path specifies a path to the log file
	Path string `json:"Path,omitempty"`

	// Size specifies a maximum size of the container log
	Size string `json:"Size,omitempty"`

	// Tag specifies a custom log tag for the container
	Tag string `json:"Tag,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this inspect log config
func (m *InspectLogConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this inspect log config based on context it is used
func (m *InspectLogConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InspectLogConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InspectLogConfig) UnmarshalBinary(b []byte) error {
	var res InspectLogConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
