// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LogConfig LogConfig represents the logging configuration of the container.
//
// swagger:model LogConfig
type LogConfig struct {

	// config
	Config map[string]string `json:"Config,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this log config
func (m *LogConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this log config based on context it is used
func (m *LogConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogConfig) UnmarshalBinary(b []byte) error {
	var res LogConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
