// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkPruneOKBody network prune o k body
//
// swagger:model networkPruneOKBody
type NetworkPruneOKBody struct {

	// networks deleted
	NetworksDeleted []string `json:"NetworksDeleted"`
}

// Validate validates this network prune o k body
func (m *NetworkPruneOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this network prune o k body based on context it is used
func (m *NetworkPruneOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkPruneOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkPruneOKBody) UnmarshalBinary(b []byte) error {
	var res NetworkPruneOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
