// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// NetworkMode NetworkMode represents the container network stack.
//
// swagger:model NetworkMode
type NetworkMode string

// Validate validates this network mode
func (m NetworkMode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this network mode based on context it is used
func (m NetworkMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
