// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecretCreateLibpodCreatedBody secret create libpod created body
//
// swagger:model secretCreateLibpodCreatedBody
type SecretCreateLibpodCreatedBody struct {

	// ID
	ID string `json:"ID,omitempty"`
}

// Validate validates this secret create libpod created body
func (m *SecretCreateLibpodCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret create libpod created body based on context it is used
func (m *SecretCreateLibpodCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretCreateLibpodCreatedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretCreateLibpodCreatedBody) UnmarshalBinary(b []byte) error {
	var res SecretCreateLibpodCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
