// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecretDriverSpec secret driver spec
//
// swagger:model SecretDriverSpec
type SecretDriverSpec struct {

	// name
	Name string `json:"Name,omitempty"`

	// options
	Options map[string]string `json:"Options,omitempty"`
}

// Validate validates this secret driver spec
func (m *SecretDriverSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret driver spec based on context it is used
func (m *SecretDriverSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretDriverSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretDriverSpec) UnmarshalBinary(b []byte) error {
	var res SecretDriverSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
