// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecurityInfo HostInfo describes the libpod host
//
// swagger:model SecurityInfo
type SecurityInfo struct {

	// app armor enabled
	AppArmorEnabled bool `json:"apparmorEnabled,omitempty"`

	// default capabilities
	DefaultCapabilities string `json:"capabilities,omitempty"`

	// rootless
	Rootless bool `json:"rootless,omitempty"`

	// s e c c o m p enabled
	SECCOMPEnabled bool `json:"seccompEnabled,omitempty"`

	// s e c c o m p profile path
	SECCOMPProfilePath string `json:"seccompProfilePath,omitempty"`

	// s e linux enabled
	SELinuxEnabled bool `json:"selinuxEnabled,omitempty"`
}

// Validate validates this security info
func (m *SecurityInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this security info based on context it is used
func (m *SecurityInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecurityInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecurityInfo) UnmarshalBinary(b []byte) error {
	var res SecurityInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
